#' NLCD details

col_lc <- data.frame(
  class = c(
    "water",
    "water",
    "developed",
    "developed",
    "developed",
    "developed",
    "barren",
    "forest",
    "forest",
    "forest",
    "shrubland",
    "shrubland",
    "herbaceous",
    "herbaceous",
    "herbaceous",
    "herbaceous",
    "planted",
    "planted",
    "wetlands",
    "wetlands",
    NA
  ),
  code = c(
    11,
    12,
    21,
    22,
    23,
    24,
    31,
    41,
    42,
    43,
    51,
    52,
    71,
    72,
    73,
    74,
    81,
    82,
    90,
    95,
    0
  ),
  description = c(
    "Open Water",
    "Perennial Ice/Snow",
    "Developed, Open Space",
    "Developed, Low Intensity",
    "Developed, Medium Intensity",
    "Developed, High Intensity",
    "Barren Land (Rock/Sand/Clay)",
    "Deciduous Forest",
    "Evergreen Forest",
    "Mixed Forest",
    "Dwarf Scrub",
    "Scrub/Shrub",
    "Grassland/Herbaceous",
    "Sedge/Herbaceuous",
    "Lichens",
    "Moss",
    "Pasture/Hay",
    "Sedge/Herbaceuous",
    "woodywetlands",
    "Emergent Herbaceous Wetlands",
    "none"
  ),
  color = c(
    "#5475A8",
    "#FFFFFF",
    "#E29E8C",
    "#FF0000",
    "#B50000",
    "#D2CDC0",
    "#85C77E",
    "#38814E",
    "#38814E",
    "#AF963C",
    "#DCCA8F",
    "#FDE9AA",
    "#D1D182",
    "#A3CC51",
    "#82BA9E",
    "#82BA9E",
    "#82BA9E",
    "#FBF65D",
    "#CA9146",
    "#CA9146",
    NA
  ),
  stringsAsFactors = FALSE
)
